-- SYS4 Achievements
-- by Sys4


-- Init
local S
if (intllib) then
   dofile(minetest.get_modpath("intllib").."/intllib.lua")
   S = intllib.Getter(minetest.get_current_modname())
else
   S = function ( s ) return s end
end

if not awards then
   return
end

dofile(minetest.get_modpath("sys4_achievements").."/api.lua")

-- Achievements table définition
local a = {

   { name = 'lumberjack_begins_default',
     title = "Un bucheron en herbe",
     node = 'default:tree',
     desc = "Récolte 50 blocs de bois.",
     icon ="default_tree.png",
     type = "dig",
     target = 50,
     titems = {'default:wood', 'default:pine_wood', 'default:junglewood', 'default:acacia_wood'},
     tprizes = {'default:axe_wood', 'default:pick_wood', 'default:torch 4'},
   },

   { name = 'lumberjack_begins_jungle',
     title = "Un bucheron dans la Jungle",
     node = 'default:jungletree',
     desc = "Récolte 50 blocs de bois de jungle.",
     icon ="default_jungletree.png",
     type = "dig",
     target = 50,
     titems = {'default:wood', 'default:pine_wood', 'default:junglewood', 'default:acacia_wood'},
     tprizes = {'default:axe_wood', 'default:pick_wood', 'default:torch 4'},
   },

   { name = 'lumberjack_begins_pinetree',
     title = "Bucheron des montagnes",
     node = 'default:pine_tree',
     desc = "Récolte 50 blocs de bois de résineux.",
     icon ="default_pine_tree.png",
     type = "dig",
     target = 50,
     titems = {'default:wood', 'default:pine_wood', 'default:junglewood', 'default:acacia_wood'},
     tprizes = {'default:axe_wood', 'default:pick_wood', 'default:torch 4'},
   },

   { name = 'lumberjack_begins_acacia',
     title = "Bucheron du désert",
     node = 'default:acacia_tree',
     desc = "Récolte 50 blocs de bois d'acacia.",
     icon ="default_acacia_tree.png",
     type = "dig",
     target = 50,
     titems = {'default:wood', 'default:pine_wood', 'default:junglewood', 'default:acacia_wood'},
     tprizes = {'default:axe_wood', 'default:pick_wood', 'default:torch 4'},
   },

   { name = 'crafter_begins',
     title = "Découverte de l'artisanat",
     node = 'default:wood',
     desc = "Fabrique 50 planches",
     icon ="default_wood.png",
     type = "craft",
     target = 50,
     titems = {'default:stick', 'default:chest', 'boats:boat', 'doors:door_wood', 'doors:trapdoor'},
     tprizes = nil,
   },

   { name = 'crafter_newbee',
     title = "Artisan débutant",
     node = 'default:stick',
     desc = "Fabrique 50 sticks",
     icon ="default_stick.png",
     type = "craft",
     target = 50,
     titems = {'default:fence', 'default:ladder'},
     tprizes = nil,
   },

   { name = 'crafter_lover',
     title = "Artisan amateur",
     node = 'default:wood',
     desc = "Fabrique 100 planches de bois.",
     icon ="default_wood.png",
     type = "craft",
     target = 100,
     titems = {'default:sign_wall', 'default:pick_wood', 'default:shovel_wood', 'default:axe_wood', 'default:sword_wood'},
     tprizes = nil,
   },

   { name = 'crafter_good',
     title = "Artisan confirmé",
     node = 'default:wood',
     desc = "Fabrique 500 planches de bois.",
     icon ="default_wood.png",
     type = "craft",
     target = 500,
     titems = {'default:chest_locked'},
     tprizes = nil,
   },

   { name = 'coal_miner_begins',
     title = "Découverte du charbon",
     node = 'default:stone_with_coal',
     desc = "Récolte 50 blocs de minerai de charbon.",
     icon ="default_coal_block.png",
     type = "dig",
     target = 50,
     titems = {'default:coalblock', 'default:coal_lump'},
     tprizes = nil,
   },

   { name = 'coal_miner_newbee',
     title = "Fin des ténebres",
     node = 'default:stone_with_coal',
     desc = "Récolte 100 blocs de minerai de charbon.",
     icon ="default_coal_block.png",
     type = "dig",
     target = 100,
     titems = {'default:torch'},
     tprizes = nil,
   },

   { name = 'miner_begins',
     title = "L'age du feu",
     node = 'default:stone',
     desc = "Récolte 100 blocs de pierre.",
     icon ="default_stone.png",
     type = "dig",
     target = 100,
     titems = {'default:furnace'},
     tprizes = nil,
   },

   { name = 'miner_newbee',
     title = "L'age de pierre",
     node = 'default:stone',
     desc = "Récolte 200 blocs de pierre.",
     icon ="default_stone.png",
     type = "dig",
     target = 200,
     titems = {'default:pick_stone', 'default:shovel_stone', 'default:axe_stone', 'default:sword_stone'},
     tprizes = nil,
   },

   { name = 'stone_builder_begins',
     title = "Batisseur en herbe",
     node = 'default:cobblestone',
     desc = "Place 50 blocs de cailloux.",
     icon ="default_stone.png",
     type = "place",
     target = 50,
     titems = {'default:stonebrick'},
     tprizes = nil,
   },

   { name = 'desertstone_builder_begins',
     title = "Batisseur du désert en herbe",
     node = 'default:desert_stone',
     desc = "Place 50 blocs de pierre du désert.",
     icon ="default_desert_stone.png",
     type = "place",
     target = 50,
     titems = {'default:desert_stonebrick'},
     tprizes = nil,
   },

   { name = 'snow_miner_begins',
     title = "Découverte de la neige",
     node = 'default:snow',
     desc = "Récolte 50 blocs de neige.",
     icon ="default_snow.png",
     type = "dig",
     target = 50,
     titems = {'default:snow', 'default:snowblock'},
     tprizes = nil,
   },

   { name = 'pick_crafter_begins',
     title = "Artisanat des pioches - Découverte -",
     node = 'default:pick_stone',
     desc = "Fabrique 10 pioches en pierres.",
     icon ="default_tool_steelpick.png",
     type = "craft",
     target = 10,
     titems = {'default:pick_steel'},
     tprizes = nil,
   },

   { name = 'shovel_crafter_begins',
     title = "Artisanat des pelles - Découverte -",
     node = 'default:shovel_stone',
     desc = "Fabrique 10 pelles en pierres.",
     icon ="default_tool_steelshovel.png",
     type = "craft",
     target = 10,
     titems = {'default:shovel_steel'},
     tprizes = nil,
   },

   { name = 'axe_crafter_begins',
     title = "Artisanat des haches - Découverte -",
     node = 'default:axe_stone',
     desc = "Fabrique 10 haches en pierres.",
     icon ="default_tool_steelaxe.png",
     type = "craft",
     target = 10,
     titems = {'default:axe_steel'},
     tprizes = nil,
   },

   { name = 'sword_crafter_begins',
     title = "Artisanat des épées - Découverte -",
     node = 'default:sword_stone',
     desc = "Fabrique 10 épées en pierres.",
     icon ="default_tool_steelsword.png",
     type = "craft",
     target = 10,
     titems = {'default:sword_steel'},
     tprizes = nil,
   },

   { name = 'pick_crafter_newbee',
     title = "Artisanat des pioches - Débutant -",
     node = 'default:pick_steel',
     desc = "Fabrique 10 pioches en fer.",
     icon ="default_tool_bronzepick.png",
     type = "craft",
     target = 10,
     titems = {'default:pick_bronze'},
     tprizes = nil,
   },

   { name = 'shovel_crafter_newbee',
     title = "Artisanat des pelles - Débutant -",
     node = 'default:shovel_steel',
     desc = "Fabrique 10 pelles en fer.",
     icon ="default_tool_bronzeshovel.png",
     type = "craft",
     target = 10,
     titems = {'default:shovel_bronze'},
     tprizes = nil,
   },

   { name = 'axe_crafter_newbee',
     title = "Artisanat des haches - Débutant -",
     node = 'default:axe_steel',
     desc = "Fabrique 10 haches en fer.",
     icon ="default_tool_bronzeaxe.png",
     type = "craft",
     target = 10,
     titems = {'default:axe_bronze'},
     tprizes = nil,
   },

   { name = 'sword_crafter_newbee',
     title = "Artisanat des épées - Débutant -",
     node = 'default:sword_steel',
     desc = "Fabrique 10 épées en fer.",
     icon ="default_tool_bronzesword.png",
     type = "craft",
     target = 10,
     titems = {'default:sword_bronze'},
     tprizes = nil,
   },

   { name = 'pick_crafter_lover',
     title = "Artisanat des pioches - Amateur -",
     node = 'default:pick_bronze',
     desc = "Fabrique 10 pioches en bronze.",
     icon ="default_tool_mesepick.png",
     type = "craft",
     target = 10,
     titems = {'default:pick_mese'},
     tprizes = nil,
   },

   { name = 'shovel_crafter_lover',
     title = "Artisanat des pelles - Amateur -",
     node = 'default:shovel_bronze',
     desc = "Fabrique 10 pelles en bronze.",
     icon ="default_tool_meseshovel.png",
     type = "craft",
     target = 10,
     titems = {'default:shovel_mese'},
     tprizes = nil,
   },

   { name = 'axe_crafter_lover',
     title = "Artisanat des haches - Amateur -",
     node = 'default:axe_bronze',
     desc = "Fabrique 10 haches en bronze.",
     icon ="default_tool_meseaxe.png",
     type = "craft",
     target = 10,
     titems = {'default:axe_mese'},
     tprizes = nil,
   },

   { name = 'sword_crafter_lover',
     title = "Artisanat des épées - Amateur -",
     node = 'default:sword_bronze',
     desc = "Fabrique 10 épées en bronze.",
     icon ="default_tool_mesesword.png",
     type = "craft",
     target = 10,
     titems = {'default:sword_mese'},
     tprizes = nil,
   },

   { name = 'pick_crafter_pro',
     title = "Artisanat des pioches - Professionnel -",
     node = 'default:pick_mese',
     desc = "Fabrique 10 pioches en mese.",
     icon ="default_tool_diamondpick.png",
     type = "craft",
     target = 10,
     titems = {'default:pick_diamond'},
     tprizes = nil,
   },

   { name = 'shovel_crafter_pro',
     title = "Artisanat des pelles - Professionnel -",
     node = 'default:shovel_mese',
     desc = "Fabrique 10 pelles en mese.",
     icon ="default_tool_diamondshovel.png",
     type = "craft",
     target = 10,
     titems = {'default:shovel_diamond'},
     tprizes = nil,
   },

   { name = 'axe_crafter_pro',
     title = "Artisanat des haches - Professionnel -",
     node = 'default:axe_mese',
     desc = "Fabrique 10 haches en mese.",
     icon ="default_tool_diamondaxe.png",
     type = "craft",
     target = 10,
     titems = {'default:axe_diamond'},
     tprizes = nil,
   },

   { name = 'sword_crafter_pro',
     title = "Artisanat des épées - Professionnel -",
     node = 'default:sword_mese',
     desc = "Fabrique 10 épées en mese.",
     icon ="default_tool_diamondsword.png",
     type = "craft",
     target = 10,
     titems = {'default:sword_diamond'},
     tprizes = nil,
   },

   { name = 'iron_miner_begins',
     title = "L'age du fer",
     node = 'default:stone_with_iron',
     desc = "Récolte 50 blocs de minerai de fer.",
     icon ="default_mineral_iron.png",
     type = "dig",
     target = 50,
     titems = {'default:steelblock', 'default:steel_ingot', 'bucket:bucket_empty', 'doors:door_steel'},
     tprizes = nil,
   },

   { name = 'iron_miner_newbee',
     title = "Toujours plus de fer",
     node = 'default:stone_with_iron',
     desc = "Récolte 100 blocs de minerai de fer.",
     icon ="default_mineral_iron.png",
     type = "dig",
     target = 100,
     titems = {'default:rail'},
     tprizes = nil,
   },

   { name = 'copper_miner_begins',
     title = "l'age du cuivre",
     node = 'default:stone_with_copper',
     desc = "Récolte 50 blocs de minerai de cuivre.",
     icon ="default_mineral_copper.png",
     type = "dig",
     target = 50,
     titems = {'default:copperblock', 'default:copper_ingot'},
     tprizes = nil,
   },

   { name = "l'age du bronze",
     title = "Mineur de cuivre - Débutant -",
     node = 'default:stone_with_copper',
     desc = "Récolte 100 blocs de minerai de cuivre.",
     icon ="default_mineral_copper.png",
     type = "dig",
     target = 100,
     titems = {'default:bronze_ingot'},
     tprizes = nil,
   },

   { name = 'bronze_crafter_begins',
     title = "L'apogée du bronze",
     node = 'default:bronze_ingot',
     desc = "Fabrique 50 lingots de bronze.",
     icon ="default_bronze_ingot.png",
     type = "craft",
     target = 50,
     titems = {'default:bronzeblock'},
     tprizes = nil,
   },

   { name = 'gold_miner_begins',
     title = "Chercheur d'or",
     node = 'default:stone_with_gold',
     desc = "Récolte 50 blocs de pierres avec minerai d'or.",
     icon ="default_mineral_gold.png",
     type = "dig",
     target = 50,
     titems = {'default:goldblock', 'default:gold_ingot'},
     tprizes = nil,
   },

   { name = 'diamond_miner_begins',
     title = "Mineur des bas fonds",
     node = 'default:stone_with_diamond',
     desc = "Récolte 50 blocs de pierres avec des diamants.",
     icon ="default_mineral_diamond.png",
     type = "dig",
     target = 50,
     titems = {'default:diamondblock', 'default:diamond'},
     tprizes = nil,
   },

   { name = 'mese_miner_begins',
     title = "chercheur de mese",
     node = 'default:stone_with_mese',
     desc = "Récolte 50 blocs de pierres avec du mese.",
     icon ="default_mineral_mese.png",
     type = "dig",
     target = 50,
     titems = {'default:mese_crystal_fragment', 'default:mese_crystal'},
     tprizes = nil,
   },

   { name = 'mese_crafter_begins',
     title = "Mese bien sur ?",
     node = 'default:mese',
     desc = "Fabrique 50 blocs de mese.",
     icon ="default_mese_block.png",
     type = "craft",
     target = 50,
     titems = {'default:meselamp'},
     tprizes = nil,
   },

   { name = 'obsidian_miner_begins',
     title = "C'est dur l'obsidienne",
     node = 'default:obsidian',
     desc = "Récolte 50 blocs d'obsidienne.",
     icon ="default_obsidian.png",
     type = "dig",
     target = 50,
     titems = {'default:obsidian_shard', 'default:obsidian', 'doors:door_obsidian_glass'},
     tprizes = nil,
   },

   { name = 'obsidian_builder_begins',
     title = "Batisseur à l'obsidienne",
     node = 'default:obsidian',
     desc = "Place 50 blocs d'obsidienne.",
     icon ="default_obsidian.png",
     type = "place",
     target = 50,
     titems = {'default:obsidianbrick'},
     tprizes = nil,
   },

   { name = 'sand_miner_begins',
     title = "Au gré des sables",
     node = 'default:sand',
     desc = "Récolte 100 blocs de sable.",
     icon ="default_sand.png",
     type = "dig",
     target = 100,
     titems = {'default:sandstone', 'default:sand', 'doors:door_glass'},
     tprizes = nil,
   },

   { name = 'sand_crafter_begins',
     title = "Maitre du gré",
     node = 'default:sandstone',
     desc = "Fabrique 50 blocs gré.",
     icon ="default_sandstone.png",
     type = "craft",
     target = 50,
     titems = {'default:sandstonebrick'},
     tprizes = nil,
   },

   { name = 'clay_miner_begins',
     title = "Découverte de l'argile",
     node = 'default:clay',
     desc = "Récolte 50 blocs d'argile.",
     icon ="default_clay.png",
     type = "dig",
     target = 50,
     titems = {'default:clay', 'default:clay_lump'},
     tprizes = nil,
   },

   { name = 'clay_builder_begins',
     title = "Terre cuite - Découverte -",
     node = 'default:clay',
     desc = "Place 50 blocs d'argile.",
     icon ="default_clay.png",
     type = "place",
     target = 50,
     titems = {'default:brick', 'default:clay_brick'},
     tprizes = nil,
   },

   { name = 'papyrus_miner_begins',
     title = "Vos papiers !",
     node = 'default:papyrus',
     desc = "Récolte 50 papyrus.",
     icon ="default_papyrus.png",
     type = "dig",
     target = 50,
     titems = {'default:paper'},
     tprizes = nil,
   },

   { name = 'book_crafter_begins',
     title = "Vous savez écrire",
     node = 'default:paper',
     desc = "Fabrique 50 feuilles de papier.",
     icon ="default_book.png",
     type = "craft",
     target = 50,
     titems = {'default:book'},
     tprizes = nil,
   },

   { name = 'book_crafter_newbee',
     title = "La passion du livre",
     node = 'default:book',
     desc = "Fabrique 10 livres.",
     icon ="default_book.png",
     type = "craft",
     target = 10,
     titems = {'default:bookshelf'},
     tprizes = nil,
   },
}

if farming then
   table.insert(a,
		{ name = 'agro_begins',
		  title = "Découverte de l'agriculture",
		  node = 'default:grass_1',
		  desc = "Récolte 50 touffes d'herbes",
		  icon = "farming_tool_woodhoe.png",
		  type = "dig",
		  target = 50,
		  titems = {'farming:hoe_wood'},
		  tprizes = nil
		})
end

   -- Register achievements from table
for i=1, #a do
   awards.register_achievement(
      a[i].name,
      {
	 title = a[i].title,
	 description = a[i].desc ,
	 icon = a[i].icon,
	 trigger = { type = a[i].type, node = a[i].node, target = a[i].target },
	 items = a[i].titems,
	 prizes = a[i].tprizes,
	 book = { title = "SYS4 AWARDS : "..a[i].title,
		  text = sys4_achievements.write_book(a[i].titems, a[i].tprizes)
	 },
      })
end
   
